name: "Lint GitHub Actions workflows"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "58 5 * * 1"
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: actionlint-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  actionlint:
    name: actionlint
    runs-on: ubuntu-latest
    permissions:
      contents: read # only needed to check out the repo
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Enable actionlint inline annotations
        run: echo "::add-matcher::.github/actionlint-matcher.json"

      # Official Docker image, pinned by digest for reproducibility.
      # Digest corresponds to v1.7.12 (latest as of 2026-09-11).
      - name: Check workflow files with actionlint
        uses: docker://rhysd/actionlint@sha256:b1934ee5f1c509618f2508e6eb47ee0d3520686341fec936f3b79331f9315667 # v1.7.12
        with:
          args: -color
